"use client";

import './global.css';
import { AppNavbar, AppFooter } from '@gs-app/ui';

// export const metadata = {
//   title: 'Welcome to ',
//   description: 'Generated by create-nx-workspace',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <AppNavbar />
        <main className="flex-grow">
        {children}
        </main>
      <AppFooter />
      </body>
    </html>
  );
}
