"use client";

import './global.css';
import { AppNavbar } from '@gs-app/ui';

// export const metadata = {
//   title: 'Welcome to ',
//   description: 'Generated by create-nx-workspace',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppNavbar />
        {children}
      </body>
    </html>
  );
}
