"use client";

import './global.css';
import { AppNavbar, AppFooter } from '@gs-app/ui';
import { Urbanist } from 'next/font/google';

// export const metadata = {
//   title: 'Welcome to ',
//   description: 'Generated by create-nx-workspace',
// };

const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist',
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={urbanist.variable}>
      <body className="flex flex-col min-h-screen">
        <AppNavbar />
        <main className="flex-grow">
        {children}
        </main>
      <AppFooter />
      </body>
    </html>
  );
}
